
compiler: ghcjs-0.2.0.20151230.3_ghc-7.10.2
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20151230.3_ghc-7.10.2:
    url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20151230.3/ghcjs-0.2.0.20151230.3.tar.gz"
packages:
- '.'
- location: '..'
  subdirs:
  - lubeck-core
  - lubeck-frp
  - lubeck-drawing
  - lubeck-dv
  - lubeck-web
- location:
    git: git@github.com:ghcjs/ghcjs-ffiqq.git
    commit: da31b18582542fcfceade5ef6b2aca66662b9e20
- location:
    git: git@github.com:BeautifulDestinations/virtual-dom.git
    commit: c26f38a53e727e95b6f722aac6f6844729880d73
- location:
    git: git@github.com:msakai/data-interval.git
    commit: f57e950e53e5499f1cbc2609382521bf52105b5e
- location:
    git: git@github.com:msakai/extended-reals.git
    commit: c724f6fcece279873354f576b9099579cb42f8ec
- location:
    git: https://github.com/ghcjs/ghcjs-base.git
    commit: 831bbe58540158146c3f9b4e2fa960d82b11a1b6
extra-deps: [ ListZipper-1.2.0.2 ]
resolver: lts-3.20
