flags: {}
compiler: ghcjs-0.2.0_ghc-7.10.2
packages:
- '.'
- location:
    git: git@github.com:ghcjs/ghcjs-ffiqq.git
    commit: da31b18582542fcfceade5ef6b2aca66662b9e20
- location:
    git: git@github.com:BeautifulDestinations/virtual-dom.git
    commit: bd6532d07f7d90a847ec57b69e64c92b4bd7f120
- location:
    git: git@github.com:msakai/data-interval.git
    commit: f57e950e53e5499f1cbc2609382521bf52105b5e
- location:
    git: git@github.com:msakai/extended-reals.git
    commit: c724f6fcece279873354f576b9099579cb42f8ec
extra-deps: []
resolver: nightly-2015-12-14
