flags: {}
compiler: ghcjs-0.2.0_ghc-7.10.2
packages:
- '.'
- location:
    git: git@github.com:ghcjs/ghcjs-ffiqq.git
    commit: da31b18582542fcfceade5ef6b2aca66662b9e20
- location:
    git: git@github.com:BeautifulDestinations/ghcjs-vdom.git
    commit: dd28f046713c37d7805b7997f32e861f1b85fc67
- location:
    git: git@github.com:ghcjs/ghcjs-dom.git
    commit: bbd0e70f7dae6d8d9b89b7307f2d0acf613836a7
# - location:
    # git: git@github.com:ghcjs/diagrams-ghcjs.git
    # commit: 50de0daa6a14406e5e4e57d9ccc11af8a376f410
extra-deps:
resolver: nightly-2015-12-14
