flags: {}
compiler: ghcjs-0.2.0_ghc-7.10.2
packages:
- '.'
- location:
    git: git@github.com:ghcjs/ghcjs-ffiqq.git
    commit: da31b18582542fcfceade5ef6b2aca66662b9e20
- location:
    git: git@github.com:BeautifulDestinations/virtual-dom.git
    commit: c78bd4eb292b53a870f6d8f0dee8aff7c14ac3f8
- location:
    git: git@github.com:msakai/data-interval.git
    commit: f57e950e53e5499f1cbc2609382521bf52105b5e
- location:
    git: git@github.com:msakai/extended-reals.git
    commit: c724f6fcece279873354f576b9099579cb42f8ec
- location:
    git: https://github.com/EugeneN/ghcjs-base.git
    commit: 861ef792b91063cf01daa573bcb4d96f4db0cf09
extra-deps: []
resolver: nightly-2015-12-14
